### ISSUE TITLE
RMLUI Invalid entity bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-js-module#237]
### Description of the problem

Hi.

I create RMLUI successfully but getElementByID does not return correct value.

Error message: 
[02:38:55][Error] GetEntity: Invalid entity with type 
[02:38:55][Error] GetEntity: Invalid entity with type 
[02:38:55][Error] [V8] Exception at one_hud:nametag.mjs:99
[02:38:55][Error]   		nametagRML.getElementByID("npcNames").appendChild(rml);
[02:38:55][Error]   TypeError: Cannot read properties of null (reading 'appendChild')
    at createNpcRml (nametag.mjs:99:40)
    at nametag.mjs:243:33

### Reproduction steps

Code:
let nametagRML = new alt.RmlDocument('/rml/nametag.rml');
const rml = nametagRML.createElement('div');
nametagRML.getElementByID("npcNames").appendChild(rml);

### Expected behaviour

The code works in the release branch, and a few days ago it even worked in the rc branch.

### Operating system

Windows 11

### Version

13.0-rc11, branch rc

### Scope

client

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by ZackaryH8** [comment]
I am also having this issue, it just returns null

**Comment by C0kkie** [comment]
Fixed in newest dev
